#!/bin/bash
sudo apt-get update
sudo apt-get install unzip
wget https://codeload.github.com/ikhsannugs/Project-Cilsy-AWS/zip/master
sudo unzip /master
sudo chmod 500 /Project-Cilsy-AWS-master/webserver.sh
/bin/bash /Project-Cilsy-AWS-master/webserver.sh

#!/bin/bash
sudo apt-get update
sudo apt-get install unzip
wget https://codeload.github.com/ikhsannugs/Project-Cilsy-AWS/zip/master
sudo unzip /master
sudo chmod 500 /Project-Cilsy-AWS-master/loadbalance.sh
/bin/bash /Project-Cilsy-AWS-master/loadbalance.sh
